### ISSUE TITLE
[@toast-ui/vue-grid] formatter 사용 질문

### ISSUE THREAD

**Issue by ingcco** [nhn/toast-ui.vue-grid#2]
안녕하세요 최근 뷰를 공부하면서 grid 라이브러리를 찾다가 

vue tui grid 사용에 대해서 궁금한 점이 있어 질문드립니다.

vue에서 tuiGrid를 임포트한 다음 

columns에 formatter 함수를 이용하여 인풋 타입의 그리드나 버튼을 넣어 

CRUD 기능을 커스텀하여 사용하고 싶지만 github 문서에서 따로 formatter에 관한 옵션이나 자료를 찾을 수 없어서 

혹시 관련 자료나 예제 소스에 관한 정보를 알 수 있을까요?! 

`
<template>
   ref="tuiGrid"
        :rowData="rows"
        :columnData="columns"
        :options="options"
        @click="onClick"
        @check="onCheck"
        @dblclick="onDoubleClick"
        >
        </grid>
    </div>
</template>

<script>
    import "tui-grid/dist/tui-grid.css";
    import { Grid } from "@toast-ui/vue-grid";
    import axios from 'axios';

    export default {
        components: {
            grid: Grid
        },
        data() {
            return {
                rows: [ // for rowData prop
                    {
                        name: 'Beautiful Lies',
                        artist: 'Birdy',
                    },
                    {
                        name: 'X',
                        artist: 'Ed Sheeran'
                    }
                ],
                columns: [ // for columnData prop
                    {
                        title: 'Name',
                        name: 'name',
                    },
                    {
                        title: 'Artist',
                        name: 'artist',
                        formatter : function(){
                            return '<input id="zz" style="z-index:100;"placeholder="input format" v-model="inputTest"></input>';
                        },
                    }
                ],
                options: {
                    editingEvent: true,
                    bodyHeight : 500,
                    scrollX: true,
                    scrollY: true,
                    rowHeight: 15,
                    rowHeaders: ["checkbox"]
                },
                dialog: false,
                selectedRow: null,
                inputTest: null
            };
        }
</script>
`

**Comment by jungeun-cho** [comment]
안녕하세요. Formatter 관련 내용은
http://nhnent.github.io/tui.grid/latest/tutorial-example02-formatter
이쪽 예제를 참고해주세요~!ㅎㅎ

**Comment by deadlockk** [comment]
> 안녕하세요. Formatter 관련 내용은
> http://nhnent.github.io/tui.grid/latest/tutorial-example02-formatter
> 이쪽 예제를 참고해주세요~!ㅎㅎ

링크가 막혀 있는데 다시 알려주실 수 있을까요?
