### ISSUE TITLE
addClassName 반영되지 않습니다.

### ISSUE THREAD

**Issue by hiphopddori** [nhn/toast-ui.vue-grid#3]
## Version
1.0.3
## Test Environment
크롬 , 맥 모하비

## Current Behavior

``
  < div>
            <v-btn color="info"  @click='gridControl("cell_color_change")'>cell color change</v-btn>
            <v-btn color="info"  @click='gridControl("get_value")'>Get Value</v-btn>
        < div>
            < grid ref="tuiGrid" :rowData="data" :columnData="columns" />
        </ div >
 </ div  > 
``
gridControl(flag){
            if (flag == "get_value" ){
                let row = this.$refs.tuiGrid.invoke('getValue','1','artist',true);
                alert(row);
            }else if (flag == "cell_color_change"){
                this.$refs.tuiGrid.invoke('addCellClassName', '1','artist','cell-red');
            }   
}

<style>
    .tui-grid-cell.cell-red {background-color: red}
</style>
``
위 테스트 코드로 테스트하고있는데 실제 다른 메소드들은 잘 작동하는데 에를들어
getValue나 getRows등 원하는값들이 잘 출력되는데
배경색을 바꾸기 위해 addClassName을 호출하였을경우 반영이 안되고있습니다.
크롬 요소검사에서 수동으로 cell-red를 추가하였을시 배경색이 잘 변경되는것을 확인하였습니다.
해당 메소드가 정상 작동 하지 않는거 같습니다.

## Expected Behavior
addClassName호출시 바로 원하는 클래스가 해당 셀에 추가되었으면 합니다.

**Comment by jungeun-cho** [comment]
[vue-wrapper 1.0.4](https://github.com/nhnent/toast-ui.vue-grid/releases/tag/v1.0.4)에 반영되었습니다.
